@startmindmap
* AHT Sobre nós
** 1. Escrever texto falando sobre a empresa
** 2. Aplicar estilo de design
***2.1 Aplicar a logo
***2.2 Aplicar o estilo design já utilizado nas outras páginas do site
**3. Selecionar as imagens necessárias
**4. Criar um protótipo no figma
**5. Codar a página em html, css e javascript
@endmindmap
