@startmindmap
* AHT Galeria
** 1. Criar Abas para as fotos dos campeonatos antigos
*** 1.1 Separar fotos por edições
** 2. Criar Aba para a competição atual
** 3. Definir a locação de cada elementos nas paginas
** 4. Usar Design das outras paginas para criação dessa
*** 4.1 Adicionar as fotos nas abas
*** 4.2 Fotos do Ambiente, Equipes participantes e CANSAT
** 5. Programar usando HTML, CSS, javascript
@endmindmap